"""
Convert AIRBOT MCAP dataset to LeRobot format.

Adapted from the official airbot-pi0 convert_mcap_data_to_lerobot.py.
Produces feature names compatible with this repo's data pipeline:
  observation.state, action, observation.images.{cam_high,cam_left_wrist,cam_right_wrist}

Usage:
    uv run examples/airbot/convert_mcap_to_lerobot.py \\
        --mcap-dir /path/to/260413_block_handover \\
        --repo-id myorg/block-handover

The MCAP directory may contain .mcap files directly or in one level of subdirectories.
Each .mcap file is treated as one episode.

Dependencies (beyond standard openpi deps):
    uv pip install mcap flatbuffers
"""

import dataclasses
import os
from pathlib import Path
import shutil
import tempfile
from typing import Literal

import cv2
from lerobot.common.datasets.lerobot_dataset import LeRobotDataset
from mcap.reader import make_reader
import numpy as np
import tqdm
import tyro

# ---------------------------------------------------------------------------
# Embedded FlatBuffers decoder for airbot_fbs.FloatArray
# (auto-generated by the FlatBuffers compiler)
# ---------------------------------------------------------------------------
import flatbuffers


class FloatArray:
    __slots__ = ["_tab"]

    @classmethod
    def GetRootAsFloatArray(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = cls()
        x._tab = flatbuffers.table.Table(buf, n + offset)
        return x

    def ValuesAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Float32Flags, o)
        return np.array([], dtype=np.float32)


# ---------------------------------------------------------------------------
# Default topic configuration for PTK dual-arm robot
# (follow = observed state, lead = teleoperated action)
# ---------------------------------------------------------------------------
DEFAULT_STATE_TOPICS = [
    "/left/follow/arm/joint_state/position",   # 6 joints
    "/left/follow/eef/joint_state/position",   # 1 gripper
    "/right/follow/arm/joint_state/position",  # 6 joints
    "/right/follow/eef/joint_state/position",  # 1 gripper
]

DEFAULT_ACTION_TOPICS = [
    "/left/lead/arm/joint_state/position",
    "/left/lead/eef/joint_state/position",
    "/right/lead/arm/joint_state/position",
    "/right/lead/eef/joint_state/position",
]

# MCAP attachment name → LeRobot camera key
DEFAULT_CAMERA_TOPICS: dict[str, str] = {
    "cam_high": "/env_camera/color/image_raw",
    "cam_left_wrist": "/left_camera/color/image_raw",
    "cam_right_wrist": "/right_camera/color/image_raw",
}

MOTOR_NAMES = [
    "left_waist",
    "left_shoulder",
    "left_elbow",
    "left_forearm_roll",
    "left_wrist_angle",
    "left_wrist_rotate",
    "left_gripper",
    "right_waist",
    "right_shoulder",
    "right_elbow",
    "right_forearm_roll",
    "right_wrist_angle",
    "right_wrist_rotate",
    "right_gripper",
]

LEROBOT_HOME = Path(os.getenv("LEROBOT_HOME", "~/.cache/huggingface/lerobot")).expanduser()


@dataclasses.dataclass(frozen=True)
class DatasetConfig:
    use_videos: bool = True
    tolerance_s: float = 0.0001
    image_writer_processes: int = 5
    image_writer_threads: int = 4
    video_backend: str | None = None


DEFAULT_DATASET_CONFIG = DatasetConfig()


# ---------------------------------------------------------------------------
# Dataset creation
# ---------------------------------------------------------------------------

def create_empty_dataset(
    repo_id: str,
    state_dim: int,
    action_dim: int,
    camera_shapes: dict[str, tuple],
    task_name: str,
    fps: int,
    mode: Literal["video", "image"] = "video",
    dataset_config: DatasetConfig = DEFAULT_DATASET_CONFIG,
) -> LeRobotDataset:
    features: dict = {
        "observation.state": {
            "dtype": "float32",
            "shape": (state_dim,),
            "names": [MOTOR_NAMES[:state_dim]],
        },
        "action": {
            "dtype": "float32",
            "shape": (action_dim,),
            "names": [MOTOR_NAMES[:action_dim]],
        },
    }

    for cam_name, shape in camera_shapes.items():
        # shape from OpenCV is (H, W, C); LeRobot stores as (C, H, W)
        h, w, c = shape
        features[f"observation.images.{cam_name}"] = {
            "dtype": mode,
            "shape": (c, h, w),
            "names": ["channels", "height", "width"],
        }

    out_path = LEROBOT_HOME / repo_id
    if out_path.exists():
        shutil.rmtree(out_path)

    return LeRobotDataset.create(
        repo_id=repo_id,
        fps=fps,
        features=features,
        use_videos=dataset_config.use_videos,
        tolerance_s=dataset_config.tolerance_s,
        image_writer_processes=dataset_config.image_writer_processes,
        image_writer_threads=dataset_config.image_writer_threads,
        video_backend=dataset_config.video_backend,
    )


# ---------------------------------------------------------------------------
# MCAP helpers
# ---------------------------------------------------------------------------

def _save_temp_video(data: bytes) -> str:
    with tempfile.NamedTemporaryFile(suffix=".mp4", delete=False) as f:
        f.write(data)
    return f.name


def _read_frame(video_path: str, frame_idx: int) -> np.ndarray:
    cap = cv2.VideoCapture(video_path)
    total = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
    idx = min(frame_idx, total - 1)
    cap.set(cv2.CAP_PROP_POS_FRAMES, idx)
    ret, frame = cap.read()
    cap.release()
    if not ret:
        raise ValueError(f"Cannot read frame {frame_idx} from {video_path}")
    return cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)


def _find_mcap_files(mcap_dir: Path) -> list[Path]:
    """Return sorted list of .mcap files in mcap_dir (direct children only)."""
    files = sorted(
        f for f in mcap_dir.iterdir() if f.is_file() and f.suffix.lower() == ".mcap"
    )
    return files


def _read_task_name(mcap_path: Path) -> str:
    with mcap_path.open("rb") as f:
        reader = make_reader(f)
        for md in reader.iter_metadata():
            if md.name == "task_info":
                return md.metadata.get("task_description", "do the task")
    return "do the task"


def _probe_dims(
    mcap_path: Path,
    state_topics: list[str],
    action_topics: list[str],
    camera_topics: dict[str, str],
) -> tuple[int, int, dict[str, tuple]]:
    """Read one MCAP file to determine state_dim, action_dim, and camera shapes."""
    fbs_decoder = FloatArray.GetRootAsFloatArray
    state_dim = 0
    action_dim = 0
    camera_shapes: dict[str, tuple] = {}
    all_topics = state_topics + action_topics

    with mcap_path.open("rb") as f:
        reader = make_reader(f)

        # Camera shapes from attachments
        tmp_paths: list[str] = []
        try:
            for attach in reader.iter_attachments():
                if attach.media_type != "video/mp4":
                    continue
                for cam_name, topic in camera_topics.items():
                    if attach.name == topic and cam_name not in camera_shapes:
                        tmp = _save_temp_video(attach.data)
                        tmp_paths.append(tmp)
                        frame = _read_frame(tmp, 0)
                        camera_shapes[cam_name] = frame.shape  # (H, W, C)
        finally:
            for p in tmp_paths:
                try:
                    os.unlink(p)
                except OSError:
                    pass

        # State/action dims from first messages
        seen: set[str] = set()
        for schema_obj, channel_obj, message_obj in reader.iter_messages(topics=all_topics):
            if channel_obj.topic in seen:
                continue
            seen.add(channel_obj.topic)
            vals = fbs_decoder(message_obj.data).ValuesAsNumpy()
            if channel_obj.topic in state_topics:
                state_dim += len(vals)
            else:
                action_dim += len(vals)
            if len(seen) == len(all_topics):
                break

    missing = [c for c in camera_topics if c not in camera_shapes]
    if missing:
        raise ValueError(f"Camera attachments not found: {missing}")

    return state_dim, action_dim, camera_shapes


# ---------------------------------------------------------------------------
# Episode processing
# ---------------------------------------------------------------------------

def _process_episode(
    mcap_path: Path,
    dataset: LeRobotDataset,
    state_topics: list[str],
    action_topics: list[str],
    camera_topics: dict[str, str],
    task_name: str,
) -> None:
    fbs_decoder = FloatArray.GetRootAsFloatArray
    all_topics = state_topics + action_topics
    # Reverse map: attachment name → cam key
    attach_to_cam = {v: k for k, v in camera_topics.items()}

    with mcap_path.open("rb") as f:
        reader = make_reader(f)

        # Extract all camera attachments to temp files
        cam_tmp: dict[str, str] = {}  # cam_key → tmp_path
        try:
            for attach in reader.iter_attachments():
                if attach.media_type == "video/mp4" and attach.name in attach_to_cam:
                    cam_key = attach_to_cam[attach.name]
                    cam_tmp[cam_key] = _save_temp_video(attach.data)

            if len(cam_tmp) != len(camera_topics):
                missing = set(camera_topics) - set(cam_tmp)
                print(f"  Skipping {mcap_path.name}: missing camera attachments {missing}")
                return

            # Iterate messages; save a frame whenever any topic advances 2 ahead
            cnt_topics: dict[str, int] = {t: 0 for t in all_topics}
            state_msg: dict[str, np.ndarray] = {}
            action_msg: dict[str, np.ndarray] = {}
            frame_cnt = 0

            for schema_obj, channel_obj, message_obj in reader.iter_messages(topics=all_topics):
                topic = channel_obj.topic
                cnt_topics[topic] += 1

                if cnt_topics[topic] - frame_cnt == 2:
                    _add_frame(
                        dataset, state_msg, action_msg, cam_tmp,
                        state_topics, action_topics, frame_cnt, task_name,
                    )
                    frame_cnt += 1

                vals = fbs_decoder(message_obj.data).ValuesAsNumpy()
                if topic in state_topics:
                    state_msg[topic] = vals
                elif topic in action_topics:
                    action_msg[topic] = vals

            # Save the last frame
            _add_frame(
                dataset, state_msg, action_msg, cam_tmp,
                state_topics, action_topics, frame_cnt, task_name,
            )
            dataset.save_episode()

        finally:
            for p in cam_tmp.values():
                try:
                    os.unlink(p)
                except OSError:
                    pass


def _add_frame(
    dataset: LeRobotDataset,
    state_msg: dict[str, np.ndarray],
    action_msg: dict[str, np.ndarray],
    cam_tmp: dict[str, str],
    state_topics: list[str],
    action_topics: list[str],
    frame_idx: int,
    task_name: str,
) -> None:
    # Check all topics have data
    for t in state_topics:
        if t not in state_msg:
            print(f"  Warning: missing state topic {t} at frame {frame_idx}, skipping")
            return
    for t in action_topics:
        if t not in action_msg:
            print(f"  Warning: missing action topic {t} at frame {frame_idx}, skipping")
            return

    state_vec = np.concatenate([state_msg[t] for t in state_topics]).astype(np.float32)
    action_vec = np.concatenate([action_msg[t] for t in action_topics]).astype(np.float32)

    frame: dict = {
        "observation.state": state_vec,
        "action": action_vec,
        "task": task_name,
    }
    for cam_key, tmp_path in cam_tmp.items():
        frame[f"observation.images.{cam_key}"] = _read_frame(tmp_path, frame_idx)

    dataset.add_frame(frame)


# ---------------------------------------------------------------------------
# Main conversion function
# ---------------------------------------------------------------------------

def convert_mcap_to_lerobot(
    mcap_dir: Path,
    repo_id: str,
    *,
    task_name: str = "",
    fps: int = 25,
    push_to_hub: bool = False,
    mode: Literal["video", "image"] = "video",
    episodes: list[int] | None = None,
    dataset_config: DatasetConfig = DEFAULT_DATASET_CONFIG,
) -> LeRobotDataset:
    """Convert a directory of MCAP files to a LeRobot dataset.

    Args:
        mcap_dir: Directory containing .mcap files (one per episode).
        repo_id: HuggingFace repo id, e.g. "myorg/block-handover".
        task_name: Task description string. If empty, reads from MCAP metadata.
        fps: Frames per second (default 25, matching collection config).
        push_to_hub: Whether to push the dataset to HuggingFace Hub.
        mode: Store images as "video" (mp4) or "image" (individual frames).
        episodes: Subset of episode indices to convert (default: all).
        dataset_config: Image writer configuration.
    """
    state_topics = DEFAULT_STATE_TOPICS
    action_topics = DEFAULT_ACTION_TOPICS
    camera_topics = DEFAULT_CAMERA_TOPICS

    mcap_files = _find_mcap_files(mcap_dir)
    if not mcap_files:
        raise ValueError(f"No .mcap files found in {mcap_dir}")
    print(f"Found {len(mcap_files)} MCAP files in {mcap_dir}")

    if episodes is not None:
        mcap_files = [mcap_files[i] for i in episodes if i < len(mcap_files)]

    # Probe dimensions from first file
    print(f"Probing dimensions from {mcap_files[0].name} ...")
    state_dim, action_dim, camera_shapes = _probe_dims(
        mcap_files[0], state_topics, action_topics, camera_topics
    )
    print(f"  state_dim={state_dim}, action_dim={action_dim}")
    print(f"  camera_shapes={camera_shapes}")

    # Read task name from metadata if not provided
    if not task_name:
        task_name = _read_task_name(mcap_files[0])
    print(f"  task_name='{task_name}'")

    dataset = create_empty_dataset(
        repo_id=repo_id,
        state_dim=state_dim,
        action_dim=action_dim,
        camera_shapes=camera_shapes,
        task_name=task_name,
        fps=fps,
        mode=mode,
        dataset_config=dataset_config,
    )

    for mcap_path in tqdm.tqdm(mcap_files, desc="Converting episodes"):
        try:
            _process_episode(
                mcap_path, dataset,
                state_topics, action_topics, camera_topics,
                task_name,
            )
        except Exception as e:
            print(f"Error processing {mcap_path.name}: {e}")
            dataset.clear_episode_buffer()

    if push_to_hub:
        dataset.push_to_hub()

    print(f"Done. Dataset saved to {LEROBOT_HOME / repo_id}")
    return dataset


if __name__ == "__main__":
    tyro.cli(convert_mcap_to_lerobot)
